
 apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: react-app-pipeline
description: React app deployment pipeline

serialPipeline:
  stages:
    - targetId: dev
      profiles: [dev]
    - targetId: uat
      profiles: [uat]
      strategy:
        standard:
          predeploy:
            actions: []
            approval: true
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: dev
description: Development environment
gcs:
  location: gs://caitcustomerappdevelop

---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: uat
description: UAT environment
gcs:
  location: gs://caitcustomerappuat

